-- AcdanteSQLMon 等待事件知识库种子数据
-- 包含 Oracle 常见等待事件的详细解释、原因分析和处理建议

INSERT INTO wait_event_guide (event_name, wait_class, description, typical_cause, resolution, oracle_doc_url, severity, applicable_ver) VALUES
('enq: TX - row lock contention', 'Application',
 '行级事务锁竞争。当一个会话试图修改另一个会话尚未提交的行时发生。',
 '1. 长事务未提交 2. 应用逻辑导致并发更新同一行 3. 批处理作业与在线事务冲突',
 '1. 检查阻塞会话的SQL和持有时间 2. 优化应用逻辑减少行锁冲突 3. 设置合理的锁等待超时 4. 考虑使用NOWAIT或SKIP LOCKED',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/enq-TX-row-lock-contention.html',
 'critical', 'ALL'),

('enq: TM - contention', 'Application',
 '表级DML锁竞争。通常与外键约束缺失索引有关。',
 '1. 外键列缺少索引 2. LOCK TABLE语句 3. DDL操作阻塞DML',
 '1. 检查并为外键列创建索引 2. 避免长时间持有表锁',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/enq-TM-contention.html',
 'warning', 'ALL'),

('enq: HW - contention', 'Configuration',
 '高水位线(High Water Mark)锁竞争。大量并发INSERT时可能发生。',
 '1. 大量并发INSERT操作 2. 段空间管理争用',
 '1. 使用ASSM表空间 2. 分区表分散争用 3. 预分配EXTENT',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/enq-HW-contention.html',
 'warning', 'ALL'),

('cursor: pin S wait on X', 'Concurrency',
 '游标Pin争用，会话等待获取共享Pin但被独占模式持有。',
 '1. 硬解析过多 2. 高并发执行相同SQL 3. 共享池过小',
 '1. 使用绑定变量 2. 增大SHARED_POOL_SIZE 3. 设置SESSION_CACHED_CURSORS',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/cursor-pin-s-wait-on-x.html',
 'critical', 'ALL'),

('library cache lock', 'Concurrency',
 '库缓存锁。会话等待获取库缓存对象的锁。',
 '1. DDL操作（如编译存储过程）2. 硬解析 3. 共享池内存不足',
 '1. 避免高峰时段DDL 2. 使用绑定变量减少解析 3. 调整SHARED_POOL_SIZE',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/library-cache-lock.html',
 'warning', 'ALL'),

('db file sequential read', 'User I/O',
 '单块读等待。通常与索引读取有关。',
 '1. 索引范围扫描 2. 表通过ROWID访问 3. 回滚段读取',
 '1. 检查执行计划是否合理 2. 优化索引设计 3. 增大BUFFER_CACHE 4. 检查存储I/O性能',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/db-file-sequential-read.html',
 'info', 'ALL'),

('db file scattered read', 'User I/O',
 '多块读（离散读）等待。通常与全表扫描有关。',
 '1. 全表扫描 2. 缺少合适索引 3. 大量数据读取',
 '1. 添加合适索引 2. 优化SQL避免全表扫描 3. 调整DB_FILE_MULTIBLOCK_READ_COUNT',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/db-file-scattered-read.html',
 'warning', 'ALL'),

('log file sync', 'Commit',
 '日志文件同步等待。用户提交时等待LGWR将redo写入磁盘。',
 '1. 高频提交 2. Redo日志I/O慢 3. LGWR进程瓶颈',
 '1. 减少提交频率（批量提交）2. 使用快速存储存放redo日志 3. 增大redo日志文件大小',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/log-file-sync.html',
 'warning', 'ALL'),

('gc buffer busy acquire', 'Cluster',
 'RAC全局缓存缓冲区忙碌等待。多实例竞争同一数据块。',
 '1. RAC环境热点数据块 2. 序列(sequence)争用 3. 频繁更新同一数据块',
 '1. 应用分区减少跨实例访问 2. 使用CACHE序列 3. 反向键索引',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/gc-buffer-busy-acquire.html',
 'critical', 'ALL'),

('gc cr multi block request', 'Cluster',
 'RAC全局缓存一致性读多块请求。跨实例全表扫描。',
 '1. 跨实例全表扫描 2. 大表未分区',
 '1. 数据分区并固定到实例 2. 应用亲和性设计',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/gc-cr-multi-block-request.html',
 'warning', 'ALL'),

('latch: shared pool', 'Concurrency',
 '共享池闩锁争用。',
 '1. 硬解析过多 2. 共享池内存碎片 3. 高并发SQL解析',
 '1. 使用绑定变量 2. 调整SHARED_POOL_SIZE 3. 设置CURSOR_SHARING=FORCE(临时)',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/latch-shared-pool.html',
 'critical', 'ALL'),

('direct path read', 'User I/O',
 '直接路径读取。绕过Buffer Cache直接从磁盘读取。',
 '1. 大量数据排序/哈希 2. 并行查询 3. LOB读取',
 '1. 优化SQL减少排序 2. 调整PGA_AGGREGATE_TARGET',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/direct-path-read.html',
 'info', 'ALL'),

('enq: TX - allocate ITL entry', 'Configuration',
 '事务槽(ITL)分配不足。',
 '1. INITRANS设置过小 2. 高并发DML同一块',
 '1. 增大表/索引的INITRANS值 2. 使用ASSM',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/enq-TX-allocate-ITL-entry.html',
 'warning', 'ALL'),

('SQL*Net message from client', 'Idle',
 '等待客户端发送下一条请求。这是正常的空闲等待。',
 '客户端空闲或处理响应中',
 '通常无需处理，属于Idle事件',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/SQLNet-message-from-client.html',
 'info', 'ALL'),

('cell single block physical read', 'User I/O',
 'Exadata存储单元单块物理读取。',
 '1. Exadata环境索引读取 2. 存储单元缓存未命中',
 '1. 检查Exadata存储缓存 2. 优化SQL执行计划',
 'https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/cell-single-block-physical-read.html',
 'info', '19c+');
